Ajoute la gestion d'erreur pour Checkstyle

diff --git a/.github/workflows/checkstyle.yml b/.github/workflows/checkstyle.yml
--- a/.github/workflows/checkstyle.yml
+++ b/.github/workflows/checkstyle.yml
@@ -19,4 +19,4 @@ jobs:
           distribution: 'temurin'
 
       - name: Build with Maven and run Checkstyle
-        run: mvn checkstyle:check
+        run: mvn checkstyle:check || echo "Checkstyle failed" && exit 1
